# Site settings
title: Max Cantú
header-img: img/home-bg.jpg
email: max@auralabs.co
description: "Lecciones aprendidas mientras hago negocios."
baseurl: ""
url: "http://maxcantu.com"
twitter_username: maxcantu_
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
