# Site settings
title: Focus and Dominate
header-img: img/home-bg.jpg
email: max@auralabs.co
description: "Lessons learned while building businesses."
baseurl: ""
url: "http://maxcantu.com"
twitter_username: maxcantoo
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
