# Site settings
title: Max Cantú
header-img: img/home-bg.jpg
email: max@auralabs.co
description: "Lecciones aprendidas mientras hago negocios."
baseurl: "/guides"
url: "http://maxcantu.com"
twitter_username: maxcantu_
linkedin_username:  maxcantu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
